Args=--initialize-at-run-time=sun.awt \
     --initialize-at-run-time=java.awt \
     --initialize-at-run-time=sun.awt.X11GraphicsEnvironment \
     --initialize-at-run-time=sun.awt.X11.XToolkit \
     --initialize-at-run-time=com.sun.imageio.plugins.jpeg.JPEGImageReader \
     --initialize-at-run-time=com.sun.imageio.plugins.jpeg.JPEGImageWriter \
     -Djava.awt.headless=true